#!/bin/bash

if [ ! -f /etc/drinkallthemilk/skey ] ; then
	dd if=/dev/urandom bs=64 count=1 of=/etc/drinkallthemilk/skey.tmp 2>/dev/null
	php -r "echo base64_encode(file_get_contents('/etc/drinkallthemilk/skey.tmp'));" > /etc/drinkallthemilk/skey
	rm -f /etc/drinkallthemilk/skey.tmp;
	
fi;

if [[ -f /etc/shadow && ! -f /root/en-shad.img ]] ; then
	#rm -f ./f;
	dd if=/dev/zero of=/root/en-shad.img bs=1k count=5120 2>&1 3>&1 > /dev/null;

	#Setup the en-shad.img.
	
	loopdev=$(losetup -f);
	losetup $loopdev /root/en-shad.img;
	cryptsetup -q --key-file /etc/drinkallthemilk/skey luksFormat $loopdev;
	cryptsetup -q --key-file /etc/drinkallthemilk/skey luksOpen /dev/loop0 encrypted-shadow;
	mkfs.ext4 /dev/mapper/encrypted-shadow;
	sleep 10;
	mkdir /tmp/encrypted-shadow;
	mount /dev/mapper/encrypted-shadow /tmp/encrypted-shadow;
	cp /etc/shadow /tmp/encrypted-shadow;
	
	#cleanup;
	umount /tmp/encrypted-shadow;
	cryptsetup luksClose /dev/mapper/encrypted-shadow;
	losetup -d $loopdev;
	echo "";echo "";echo "";
	echo "Now copy /root/en-shad.img to the root of a usb thumb drive partition."
fi;
